# Generated by Django 6.0.6 on 2026-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_comida', models.TextField()),
                ('codigo_utilizado', models.TextField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigosQr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField()),
                ('tipo_comida', models.TextField()),
                ('utilizado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'codigos_qr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('carnet', models.TextField(primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('carrera', models.TextField()),
                ('edad_estudi', models.SmallIntegerField()),
                ('procedencia', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('anocarrera', models.TextField(db_column='anoCarrera')),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField(unique=True)),
                ('contrasena', models.TextField()),
                ('rol', models.TextField()),
                ('estado', models.BooleanField()),
                ('sesion_activa', models.BooleanField()),
                ('fotouser', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
